### PR TITLE
1.2.1 Release Fixes

### LINKED ISSUE #102: `get_meta_result()` and `get_meta_subset()` should gracefully error with invalid ellipsis params
```r
t <- tplyr_table(adsl, TRT01P) %>% 
  add_layer(
    group_count(AGEGR1, by = vars("Age Group by Sex n (%)", SEX))
  ) 

dat <- t %>% 
  build(metadata=TRUE)

get_meta_result(t, "c1_1", "var1_Placebo", "var1_Xanomeline High Dose")
```

### LINKED ISSUE #178: Metadata handling for missing subject rows
I didn't address this in #83 - and getting to the meat of it is a bit complicated.

Missing subjects creates two points of complication:

- The data being queried needs to be the population data
- The query is not just a filter, but pulling the `distinct_by` values themselves based on the filter. 

A few extras are required with this:

- [ ] A tplyr_meta object needs to have a new field added of `source` for the dataset that's queried
- [ ] The filter will be specific to the list of subject numbers

### PR DESCRIPTION
**Pull request by mstackhouse**
## 1.2.1 release updates

Closes #178 
Closes #102 

- Updated metadata to handle `add_missing_subject_rows()`
- Updated `tplyr_meta` object to have antijoin field
- Added new `add_anti_join()` function
- Updated `get_meta_subset` to handle and process anti-join metadata
- Updated vignettes with associated information.

### CODE REVIEW

File: CRAN-SUBMISSION [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Version: 1.2.0
```
Comment (elimillera) [inline CRAN-SUBMISSION:1]: What does this file do?

File: R/meta_utils.R [hunk 2]
```diff
@@ -164,13 +195,33 @@ get_meta_subset.tplyr_table <- function(x, row_id, column, add_cols = vars(USUBJ
...
-  x$target %>%
-    filter(!!!m$filters) %>%
-    select(!!!add_cols, !!!m$names)
+  # if (!inherits(add_cols, 'quosures')) {
+  #   stop("add_cols must be provided using `dplyr::vars()`", call.=FALSE)
+  # }
+  #
+  # if (length(list(...)) > 0) {
+  #   warning("Extra arguments were provided to get_meta_subset() that will not be used.")
+  # }
```
Comment (elimillera) [inline R/meta_utils.R:204]: Can you remove these comments?

File: R/meta_utils.R [hunk 3]
```diff
@@ -164,13 +195,33 @@ get_meta_subset.tplyr_table <- function(x, row_id, column, add_cols = vars(USUBJ
...
+  #     filter(!!!aj$join_meta$filters) %>%
+  #     select(!!!aj$on, !!!add_cols, !!!aj$join_meta$names)
+  #
+  #   mrg_var <- map_chr(aj$on, as_name)
+  #   names(mrg_var) <- mrg_var
+  #
+  #   out <- anti_join(pd, out, by=mrg_var)
+  # }
+  #
+  # out
```
Comment (elimillera) [inline R/meta_utils.R:225]: Same here

File: R/meta_utils.R [hunk 4]
```diff
@@ -152,9 +159,33 @@ get_meta_subset.data.frame <- function(x, row_id, column,
     stop("If querying metadata without a tplyr_table, a target must be provided", call.=FALSE)
   }
 
-  target %>%
+  if (length(list(...)) > 0) {
+    warning("Extra arguments were provided to get_meta_subset() that will not be used.")
+  }
```
Comment (elimillera) [inline R/meta_utils.R:164]: Is there a reason we allowed for the ellipsis in the first place here? Would it be easier to remove it and let R report an argument error?

File: R/meta_utils.R [hunk 5]
```diff
@@ -69,6 +69,10 @@ get_meta_result.data.frame <- function(x, row_id, column, ...) {
                 'column present in the built Tplyr dataframe'), call.=FALSE)
   }
 
+  if (length(list(...)) > 0) {
+    warning("Extra arguments were provided to get_meta_result() that will not be used.", immediate.=TRUE)
+  }
+
```
Comment (elimillera) [inline R/meta_utils.R:75]: Is there a reason we allowed for the ellipsis in the first place here? Would it be easier to remove it and let R report an argument error?

File: R/meta.R [hunk 6]
```diff
@@ -221,8 +221,93 @@ print.tplyr_meta <- function(x, ...) {
...
+#' An anti-join allows a tplyr_meta object to refer to data that should be
+#' extract from a separate dataset, like the population data of a Tplyr table,
+#' that is unavailable in the target dataset. The primary use case for this is
+#' the presentation of missing subjects, which in a Tplyr table is presented
+#' using the function `add_missing_subjects_row()`. The missing subjects
+#' themselves are not present in the target data, and are thus only available in
+#' the population data. The `add_anti_join()` function allows you to provide the
+#' meta information relevant to the population data, and then specify the `on`
+#' variable that should be used to join with the target dataset and find the
+#' values present in the population data that are missing from the target data.
```
Comment (elimillera) [inline R/meta.R:270]:
```suggestion
#' An anti-join allows a tplyr_meta object to refer to data that should be
#' extracted from a separate dataset, like the population data of a Tplyr table,
#' that is unavailable in the target dataset. The primary use case for this is
#' the presentation of missing subjects, which in a Tplyr table is presented
#' using the function `add_missing_subjects_row()`. The missing subjects
#' themselves are not present in the target data, and are thus only available in
#' the population data. The `add_anti_join()` function allows you to provide the
#' meta information relevant to the population data, and then specify the `on`
#' variable that should be used to join with the target dataset and find the
#' values present in the population data that are missing from the target data.
```

File: vignettes/metadata.Rmd [hunk 7]
```diff
@@ -119,6 +119,51 @@ cat(c("tplyr_adsl %>%\n",
 ))
 ```
 
+### Anti Joins
+
+Most data presented within a table refers back to the target dataset from which data are being summarized. In some cases, data presented may refer to information _excluded_ from the summary. This is the case when you use the **Tplyr** function `add_missing_subjects_row()`. In this case, the counts presented refer to data excluded from the target which are present into the population data. The metadata thus need to refer to that excluded data. To handle this, there's an additional field called an 'Anti Join'. Consider this example:
```
Comment (elimillera) [inline vignettes/metadata.Rmd:124]:
```suggestion
Most data presented within a table refers back to the target dataset from which data are being summarized. In some cases, data presented may refer to information _excluded_ from the summary. This is the case when you use the **Tplyr** function `add_missing_subjects_row()`. In this case, the counts presented refer to data excluded from the target which are present in the population data. The metadata thus needs to refer to that excluded data. To handle this, there's an additional field called an 'Anti Join'. Consider this example:
```

File: CRAN-SUBMISSION (hunk 1 above)
Comment (mstackhouse) [reply CRAN-SUBMISSION:1]: automated by devtools during CRAN submission. https://devtools.r-lib.org/reference/submit_cran.html

File: R/meta_utils.R (hunk 4 above)
Comment (mstackhouse) [reply R/meta_utils.R:164]: The problem is there is no error - This is reported here: https://github.com/atorus-research/Tplyr/issues/102

If something truly passes through the ellipsis, it may still process fine and just have no effect, but not produce what you expected. The ellipsis itself is necessary though because of the S3 method. So I chose to add a warning to report it.

File: R/meta_utils.R (hunk 5 above)
Comment (mstackhouse) [reply R/meta_utils.R:75]: The problem is there is no error - This is reported here: https://github.com/atorus-research/Tplyr/issues/102

If something truly passes through the ellipsis, it may still process fine and just have no effect, but not produce what you expected. The ellipsis itself is necessary though because of the S3 method. So I chose to add a warning to report it.
