### PR TITLE
Native pipe compatibility

### LINKED ISSUE #33: Native pipe compatibility
Currently layer syntax relies strictly on use of the magrittr pipe. The native pipe (`|>`) available in R >4.1.0  does not work.

### PR DESCRIPTION
**Pull request by mstackhouse**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

# Native Pipe Compatibility

This PR adds complete compatibility with the native pipe introduced to R in version 4.1.0. 

Originally, Tplyr was developed specifically to work with the tidy programming style, where an object is piped from one function call, into the next. The functionality of the pipe works by replacing the first argument on the right hand side of the pipe with the output from the left - all done using the `%>%` function from magrittr.

In R 4.1.0, [the Native pipe (`|>`) was introduced](https://www.r-bloggers.com/2021/05/the-new-r-pipe/)). While the concept and functionality in practice is largely the same (with some minor but relevant differences), the way this evaluates in practice is quite different. The native pipe (`|>`) evaluates as the R syntax is interpreted, while the magrittr pipe (`%>%`) adds levels to the traceback.

This means that:
```r
c(1,2,3) |> mean() 
```

Literally evaluates to:
```r
mean(c(1,2,3))
```

The problem in Tplyr is that the internal function `Tplyr:::modify_nested_call()` was written explicitly around handling the magrittr pipe (`%>%`). This is used within `Tplyr::add_layer()`, and the purpose is to allow the user to design a layer using the pipe syntax in one chain without having to first bind the `tplyr_table()` object to a variable.

To handle the changes, the function had to be substantially refactored. Instead of traversing the trace stack to navigate the left hand to right hand sides of the pipe, separate handling had to be introduced to examine the first argument until the `group_count()`/`group_shift()`/`group_desc()` function is hit, upon which the tplyr_table() object is inserted as the parent environment. 

From a user perspective, changes with this PR are minimal - and the impact is simply that the native pipe now functions correctly. This can be seen as follows:

```r
tplyr_table(mtcars, gear) %>% 
  add_layer(
    group_desc(mpg) %>%
      set_format_strings('Mean (SD)' = f_str('xxx (xxx)', mean, sd))
  ) %>% 
  build()
# A tibble: 1 x 6
  row_label1 var1_3      var1_4      var1_5      ord_layer_index ord_layer_1
  <chr>      <chr>       <chr>       <chr>                 <int>       <int>
1 Mean (SD)  " 16 (  3)" " 25 (  5)" " 21 (  7)"               1           1
```

```r
tplyr_table(mtcars, gear) |> 
  add_layer(
    group_desc(mpg) |>
      set_format_strings('Mean (SD)' = f_str('xxx (xxx)', mean, sd))
  ) |>
  build()
# A tibble: 1 x 6
  row_label1 var1_3      var1_4      var1_5      ord_layer_index ord_layer_1
  <chr>      <chr>       <chr>       <chr>                 <int>       <int>
1 Mean (SD)  " 16 (  3)" " 25 (  5)" " 21 (  7)"               1           1
```

This will close #33 

Additionally, I've added the magrittr pipe as an export, closing #22 

Note that unit tests were updated, and some cleaning has been done on the testing to both clean out unnecessary tests and clean up existing ones.

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -9,33 +9,83 @@
...
+#
+#     browser()
+#     # Recursively extract the left side of the magrittr call to work your way up
+#     e <- call_standardise(c)
+#     c <- modify_nested_call(call_args(e)$lhs, allowable_calls = allowable_calls, ...)
+#     # Modfify the magittr call by inserting the call retrieved from recursive command back in
+#     c <- call_modify(e, lhs=c)
+#     c
+#   }
+# }
```
Comment (elimillera) [inline R/utils.R:88]: I think we're good to remove this comment

**Review by elimillera — APPROVED** [review]
R CMD Check is looking good and I can get the native pipe to work. Looks good to go once the commented function is removed 👍
